### ISSUE TITLE
Extension incompatible with VS Code

### ISSUE THREAD

**Issue by Adamo2499** [thicco-catto/Library-of-Isaac-Extension#1]
When I try to install Library Of Isaac Extension on VS Code, I got this error:

![image](https://github.com/thicco-catto/Library-of-Isaac-Extension/assets/30226946/1e06d2d3-389a-4d4d-a20b-c3115bde427d)

**Comment by thicco-catto** [comment]
The extension is only compatible with VSCode 1.73 or greater. You can either update your VSCode, or just download the library manually like explained here https://team-compliance.gitbook.io/library-of-isaac/get-started#2.-manually-download-the-library.
