### ISSUE TITLE
LuaLS should auto-ignore the built library

### ISSUE THREAD

**Issue by calvinhobbes1010** [thicco-catto/Library-of-Isaac-Extension#2]
Any time I build a TSIL project for the first time (i.e. it creates a folder with the resulting library in it), the Lua Language Server will begin caching the library folder. For bigger projects, this can lead to LuaLS using more memory than it arguably should and potentially leading to performance issues in VSCode, especially on lower-end PCs.

To help mitigate this, I feel like this extension should automatically tell LuaLS to ignore the library folder when building it (I'd imagine through LuaLS' "workspace.ignoreDir" setting) . This behavior could even be toggled by the user in a settings menus or something like that if they want.

**Comment by thicco-catto** [comment]
The extension should already be doing exactly that.
Are you using sumneko's lua language server extension? I haven't tested others.
If you are using, does the .luarc.json file exist in your project?
